[project]
name = "deveficiente-agentes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.107.0",
    "requests>=2.32.5",
    "yfinance>=0.2.66",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
